# Generated by Django 5.2.17 on 2026-09-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_number', models.PositiveIntegerField(help_text='1st or 2nd innings')),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings_batted', to='teams.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings_bowled', to='teams.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='teams.match')),
            ],
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.PositiveIntegerField()),
                ('ball_number', models.PositiveIntegerField(help_text='1 to 6 within the over')),
                ('runs', models.PositiveIntegerField(default=0, help_text='Runs off the bat (not including extras)')),
                ('extra_type', models.CharField(blank=True, choices=[('', 'None'), ('wide', 'Wide'), ('noball', 'No Ball'), ('bye', 'Bye'), ('legbye', 'Leg Bye')], max_length=10)),
                ('extra_runs', models.PositiveIntegerField(default=0)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wicket_type', models.CharField(blank=True, choices=[('bowled', 'Bowled'), ('caught', 'Caught'), ('lbw', 'LBW'), ('runout', 'Run Out'), ('stumped', 'Stumped'), ('other', 'Other')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_faced', to='teams.player')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_bowled', to='teams.player')),
                ('player_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissals', to='teams.player')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='teams.innings')),
            ],
        ),
    ]
