# Generated by Django 5.2.17 on 2026-09-06 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_innings_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='innings',
            name='current_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bowling_innings', to='teams.player'),
        ),
        migrations.AddField(
            model_name='innings',
            name='current_non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_striking_innings', to='teams.player'),
        ),
        migrations.AddField(
            model_name='innings',
            name='current_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='striking_innings', to='teams.player'),
        ),
        migrations.AddField(
            model_name='innings',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='result_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='teams.team'),
        ),
    ]
