# Generated by Django 5.2.17 on 2026-09-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_match_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/'),
        ),
    ]
